# NKtotebag

# MySQL connection (required)
auto-config-mysql: false

host: localhost
port: 3306
dbName: minecraft_dev
user: root
password:

table-prefix: NKtotebag_

# Options

# Does the plugin reset fly time in sql db?
sql-reset-flytime: false
