# NKsort

# MySQL connection (required)
use-mysql: false
table-prefix: NKtotebag_
host: localhost
port: 3306
dbName: minecraft_dev
user: root
password: 


# Options

# The same name gave to Bungee config
server-name: 'world'

# Does the plugin reset fly time in sql db?
sql-reset-flytime: false

# Number max home per rank
ranks:
  member: 1
  vip: 2
  admin: 5